### ISSUE TITLE
cats and dogs 문의

### ISSUE THREAD

**Issue by sa3419** [jimini55/catsdogs-cloud9#1]
안녕하세요
여러 실습을 따라하다 지민님의 ECS 실습을 하게 되었어요. 
cats and dogs 하고 있습니다.
중간에 web 작업정의에서 컨테이너 추가 부분에 이미지 넣는부분이 있던데요.
ECR 도커 이미지 빌드할때는 cats dogs만 있잖아요

그래서 web 이미지는 어디서 가져오는건지 궁금하여 이슈를 남기게 되었습니다.
당연히 Add가 활성화가 안되더라구요..

답변 부탁드립니다. ㅠㅠ
![image](https://user-images.githubusercontent.com/85730661/133364528-795d2eb6-ef3d-4e08-a33b-bdb4d1239c26.png)
#web이미지삽입

**Comment by jimini55** [comment]
안녕하세요? 먼저 답변이 늦어 죄송합니다. 워크샵 관련 문의는 https://ecs-cats-dogs.workshop.aws/en/ 요 링크에서 'Report an Issue'를 활용해 주세요. web용 컨테이너 이미지는, 소스코드 및 도커파일이 cats 및 dogs와 거의 유사합니다. 그래서 굳이 cats와 dogs에서 Dockerfile을 확인하고 빌드하는 작업을 web에서도 반복하시지 않을 수 있도록, 제 레포지토리에 미리 만들어서 컨테이너 이미지로 제공하는 것입니다. 관련하여 https://ecs-cats-dogs.workshop.aws/ko/ecs/taskdef.html 페이지 상단에서 "Amazon ECR 실습에서 생성한 cats, dogs의 도커 이미지를 참조하는 catsdef, dogsdef 태스크 정의를 생성합니다. web 태스크 정의가 사용할 도커 이미지는 별도로 제공됩니다."라고 안내하고 있습니다. 참고가 되셨길 바라며, 워크샵을 활용해 주셔서 감사합니다.

**Comment by electron-volt** [comment]
@jimini55 I am doing this workshop in AWS region eu-west-1 (Ireland). In the first section of the workshop where we deploy the Cloudformation stack, I took the S3 URL and just replaced the region ap-northeast-2 with eu-west-1. It worked perfectly. 

 Later in the workshop I'm supposed to create a task definition "web" and use the image 038445823716.dkr.ecr.ap-northeast-2.amazonaws.com/web:latest. Which image can I use in the eu-west-1 region?

**Comment by jimini55** [comment]
Thank you for reaching out. eu-west-1 region uses public ECR repository, and you can try with this URI: public.ecr.aws/ecs-cats-dogs-web/web:latest.
